using System.Collections.Generic;

namespace Pipantry.Domain {
    // based on http://site.foodshare.org/site/DocServer/Food_Storage_and_Shelf_Life_Guidelines.pdf?docID=5822
    public class ShelfLifeRepository {
        private IDictionary<string, ShelfLife> shelfLifeByCategory = new Dictionary<string, ShelfLife>
        {
            { "shredded high moisture cheese", new ShelfLife { Refrigerated = 21, Frozen = 180 } },
            { "shredded low moisture cheese", new ShelfLife { Refrigerated = 30, Frozen = 180 } },
            { "high moisture cheese", new ShelfLife { Refrigerated = 14, Frozen = 180 } },
            { "string cheese", new ShelfLife { Refrigerated = 14, Frozen = 180 } },
            { "hard cheese", new ShelfLife { Refrigerated = 180, Frozen = 180 } },
            { "processed cheese", new ShelfLife { Refrigerated = 30, Frozen = 180 } },
            { "margarine", new ShelfLife { Refrigerated = 180, Frozen = 360 } },
            { "cream cheese", new ShelfLife { Refrigerated = 60 } },
            { "yogurt", new ShelfLife { Refrigerated = 14, Frozen = 30 } },
            { "cottage cheese", new ShelfLife { Refrigerated = 14 } },
            { "ricotta cheese", new ShelfLife { Refrigerated = 14 } },
            { "sour cream", new ShelfLife { Refrigerated = 14 } },
            { "butter", new ShelfLife { Refrigerated = 60, Frozen = 360 } },
            { "milk", new ShelfLife { Refrigerated = 5 } },
            { "buttermilk", new ShelfLife { Refrigerated = 10 } },
            { "half and half", new ShelfLife { Refrigerated = 3, Frozen = 120 } },
            { "heavy cream", new ShelfLife { Refrigerated = 10, Frozen = 90 } },
            { "light cream", new ShelfLife { Refrigerated = 7, Frozen = 90 } },
            { "eggs", new ShelfLife { Refrigerated = 28 } },
            { "juice", new ShelfLife { Refrigerated = 21, Frozen = 240 } },
            { "yeast", new ShelfLife { Refrigerated = 720, Frozen = 2520 } },
            { "ice cream", new ShelfLife { Frozen = 120 } },
            { "bbq sauce", new ShelfLife { Refrigerated = 360 } },
            { "honey", new ShelfLife{Refrigerated = int.MaxValue } },
            { "jam", new ShelfLife { Refrigerated = 540 } },
            { "jelly", new ShelfLife { Refrigerated = 540 } },
            { "ketchup", new ShelfLife { Refrigerated = 540 } },
            { "molasses", new ShelfLife { Refrigerated = 720 } },
            { "olives", new ShelfLife { Refrigerated = 360 } },
            { "salad dressing", new ShelfLife { Refrigerated = 360 } },
            { "salsa", new ShelfLife { Refrigerated = 360 } },
            { "spaghetti sauce", new ShelfLife { Refrigerated = 540 } },
            { "canned beans", new ShelfLife { Refrigerated = 1080 } },
            { "canned tuna", new ShelfLife { Refrigerated = 1080 } },
            { "canned salmon", new ShelfLife { Refrigerated = 180 } },
            { "canned sardines", new ShelfLife { Refrigerated = 180 } },
            { "canned crab", new ShelfLife { Refrigerated = 180 } },
            { "frosting", new ShelfLife { Refrigerated = 300 } },
            { "canned fruit", new ShelfLife { Refrigerated = 360 } },
            { "jarred sauerkraut", new ShelfLife { Refrigerated = 360 } },
            { "tomatoes", new ShelfLife { Refrigerated = 360 } },
            { "tomato sauce", new ShelfLife { Refrigerated = 360 } },
            { "jarred gravy", new ShelfLife { Refrigerated = 720 } },
            { "canned soup", new ShelfLife { Refrigerated = 720 } },
            { "jarred cream sauce", new ShelfLife { Refrigerated = 720 } },
            { "vegetables", new ShelfLife { Refrigerated = 720 } },
            { "pie filling", new ShelfLife { Refrigerated = 1080 } },
            { "pancake mix", new ShelfLife { Refrigerated = 270, Unopened = 1800 } },
            { "cake mix", new ShelfLife { Refrigerated = 360, Unopened = 1800 } },
            { "brownie mix", new ShelfLife { Refrigerated = 360, Unopened = 1800 } },
            { "baking powder", new ShelfLife { Refrigerated = 540, Unopened = 1800 } },
            { "baking soda", new ShelfLife{ Refrigerated = int.MaxValue, Unopened = int.MaxValue } },
            { "beans", new ShelfLife { Refrigerated = 360, Unopened = 10800 } },
            { "bouillon", new ShelfLife { Refrigerated = 360, Unopened = 1800 } },
            { "bread", new ShelfLife { Refrigerated = 5, Frozen = 90 } },
            { "cake", new ShelfLife { Refrigerated = 4, Frozen = 90 } },
            { "cereal", new ShelfLife { Refrigerated = 360 } },
            { "cookies", new ShelfLife { Refrigerated = 120, Frozen = 120 } },
            { "cornmeal", new ShelfLife { Refrigerated = 360, Frozen = 720 } },
            { "crackers", new ShelfLife { Refrigerated = 240, Unopened = 360 } },
            { "white flour", new ShelfLife { Refrigerated = 360, Unopened = 1800 } },
            { "whole wheat flour", new ShelfLife { Refrigerated = 90, Unopened = 1800 } },
            { "dried fruit", new ShelfLife { Refrigerated = 180, Unopened = 1800 } },
            { "macaroni and cheese", new ShelfLife { Refrigerated = 270 } },
            { "shelled nuts", new ShelfLife { Refrigerated = 180 } },
            { "nuts", new ShelfLife { Refrigerated = 180 } },
            { "oatmeal", new ShelfLife { Refrigerated = 360, Unopened = 10800 } },
            { "oil", new ShelfLife { Refrigerated = 180 } },
            { "pasta", new ShelfLife { Refrigerated = 720, Unopened = 10800 } },
            { "peanut butter", new ShelfLife { Refrigerated = 540, Unopened = 1440 } },
            { "popcorn", new ShelfLife { Refrigerated = 720, Unopened = 1800 } },
            { "microwave popcorn", new ShelfLife { Refrigerated = 360 } },
            { "instant potatoes", new ShelfLife { Refrigerated = 360, Unopened = 2520 } },
            { "brown rice", new ShelfLife { Refrigerated = 360, Frozen = 1080 } },
            { "white rice", new ShelfLife { Refrigerated = 720, Unopened = 10800 } },
            { "rice mix", new ShelfLife { Refrigerated = 180 } },
            { "shortening", new ShelfLife { Refrigerated = 240 } },
            { "spice", new ShelfLife { Refrigerated = 1440 } },
            { "stuffing mix", new ShelfLife { Refrigerated = 270 } },
            { "brown sugar", new ShelfLife{Refrigerated = 540, Unopened = int.MaxValue} },
            { "white sugar", new ShelfLife{Refrigerated = 720, Unopened = int.MaxValue} },
            { "confectioner's sugar", new ShelfLife{Refrigerated = 540, Unopened = int.MaxValue} },
            { "sugar substitute", new ShelfLife{Refrigerated = 720, Unopened = int.MaxValue} },
            { "PopTarts", new ShelfLife { Refrigerated = 270 } },
            { "PopTarts with fruit", new ShelfLife { Refrigerated = 180 } },
            { "tortillas", new ShelfLife { Refrigerated = 90, Frozen = 180 } },
            { "cocoa mix", new ShelfLife { Refrigerated = 1080, Unopened = 5400 } },
            { "liquid coffee creamer", new ShelfLife { Refrigerated = 270 } },
            { "powdered coffee creamer", new ShelfLife { Refrigerated = 720 } },
            { "ground coffee", new ShelfLife { Refrigerated = 720, Frozen = 720 } },
            { "instant coffee", new ShelfLife { Refrigerated = 360 } },
            { "bottled juice", new ShelfLife { Refrigerated = 270 } },
            { "juice box", new ShelfLife { Refrigerated = 120 } },
            { "canned juice", new ShelfLife { Refrigerated = 540 } },
            { "evaporated milk", new ShelfLife { Refrigerated = 360 } },
            { "non-fat dry milk", new ShelfLife { Refrigerated = 360, Unopened = 7200 } },
            { "sweetened milk", new ShelfLife { Refrigerated = 360 } },
            { "condensed milk", new ShelfLife { Refrigerated = 360 } },
            { "rice milk", new ShelfLife { Refrigerated = 180 } },
            { "soy milk", new ShelfLife { Refrigerated = 180, } },
            { "bagged tea", new ShelfLife { Refrigerated = 540 } },
            { "instant tea", new ShelfLife { Refrigerated = 1080 } },
            { "loose leaf tea", new ShelfLife { Refrigerated = 720 } },
            { "water", new ShelfLife{Refrigerated = int.MaxValue, Frozen = int.MaxValue, Unopened = int.MaxValue} },
            { "salmon", new ShelfLife { Refrigerated = 2, Frozen = 90 } },
            { "fish", new ShelfLife { Refrigerated = 2, Frozen = 360 } },
            { "raw shrimp", new ShelfLife { Refrigerated = 2, Frozen = 270 } },
            { "crab legs", new ShelfLife { Refrigerated = 3 } },
            { "shucked oysters", new ShelfLife { Refrigerated = 1, Frozen = 90 } },
            { "raw lobster tails", new ShelfLife { Refrigerated = 4, Frozen = 270 } },
            { "raw scallops", new ShelfLife { Refrigerated = 1, Frozen = 90 } },
            { "roast beef", new ShelfLife { Refrigerated = 3, Frozen = 360 } },
            { "steak", new ShelfLife { Refrigerated = 3, Frozen = 360 } },
            { "ground beef", new ShelfLife { Refrigerated = 2, Frozen = 270 } },
            { "roast pork", new ShelfLife { Refrigerated = 3, Frozen = 360 } },
            { "pork chops", new ShelfLife { Refrigerated = 3, Frozen = 360 } },
            { "ground pork", new ShelfLife { Refrigerated = 2, Frozen = 270 } },
            { "roast lamb", new ShelfLife { Refrigerated = 3, Frozen = 360 } },
            { "lamb chops", new ShelfLife { Refrigerated = 3, Frozen = 360 } },
            { "ground lamb", new ShelfLife { Refrigerated = 2, Frozen = 270 } },
            { "poultry", new ShelfLife { Refrigerated = 2, Frozen = 360 } },
            { "ground poultry", new ShelfLife { Refrigerated = 2, Frozen = 270 } },
            { "bacon", new ShelfLife { Refrigerated = 7, Frozen = 180, Unopened = 14 } },
            { "ham", new ShelfLife { Refrigerated = 7, Frozen = 360, Unopened = 14 } },
            { "hot dogs", new ShelfLife { Refrigerated = 14, Frozen = 270 } },
            { "lunch meat", new ShelfLife { Refrigerated = 3, Frozen = 60, Unopened = 14 } },
            { "pepperoni", new ShelfLife { Refrigerated = 30, Unopened = 180 } },
            { "salami", new ShelfLife { Refrigerated = 30, Unopened = 180 } },
            { "raw sausage", new ShelfLife { Refrigerated = 2, Frozen = 180 } },
            { "sausage", new ShelfLife { Refrigerated = 7, Frozen = 270 } }
        };

        public bool ContainsKey(string category) {
            return shelfLifeByCategory.ContainsKey(category);
        }

        public ShelfLife this[string category] { get { return shelfLifeByCategory[category]; } }

        public void add(string category, ShelfLife shelfLife) {
            shelfLifeByCategory[category] = shelfLife;
        }
    }
}
